SELECT        dbo.JY64300V.PERSONNUMMER_RED AS CPR, dbo.JY64300V.KOMMUNENUMMER, dbo.JY64300V.FODSEL_DATO AS FOEDSELSDATO, 
                         dbo.JY64300V.KON AS KOEN, RTRIM(dbo.JY64300V.STILLING) AS STILLING, dbo.JY64300V.STILLING_DATO AS STILLINGSDATO, 
                         CAST(RTRIM(REVERSE(REPLACE(SUBSTRING(REVERSE(dbo.JY64300V.ADRESSERINGSNAVN), 1, CHARINDEX(',', REVERSE(dbo.JY64300V.ADRESSERINGSNAVN))), 
                         ',', ''))) + ' ' + REPLACE(SUBSTRING(dbo.JY64300V.ADRESSERINGSNAVN, 1, CHARINDEX(',', dbo.JY64300V.ADRESSERINGSNAVN)), ',', '') AS VARCHAR(50)) AS NAVN, 
                         dbo.JY64300V.ADRNAVN_DATO AS DATO_FOR_ADRESSERINGSNAVN, 
                         CAST(RTRIM(dbo.JY72000V.VEJADRNAVN + ' ' + REPLACE(LTRIM(REPLACE(RTRIM(dbo.JY72000V.HUS_NR), '0', ' ')), ' ', '0') 
                         + ' ' + RTRIM(LTRIM(dbo.JY64300V.ETAGE)) + ' ' + RTRIM(LTRIM(dbo.JY64300V.SIDE_DORNR))) AS VARCHAR(50)) AS ADRESSE, RTRIM(dbo.JY72000V.SUPBYNAVN) AS SUPBYNAVN, 
                         dbo.JY72000V.POSTNR, dbo.JY72000V.POSTBYNAVN, RTRIM(dbo.JY72000V.BYGNAVN) AS BYGNAVN, dbo.JY64300V.FOLKEKIRK_TILH_MRK AS FOLKEKIRKEMARKERING, 
                         dbo.JY64300V.FOLKEKIRK_MRK_DATO AS DATO_FOR_FOLKEKIRKEMARKERING, RTRIM(CAST(dbo.QL58900V.TEKST AS VARCHAR(75))) AS BORGERSTATUS, 
                         dbo.JY64300V.BORGERSTATUS_TS AS TIDSSTEMPLING_BORGERSTATUS, dbo.JY64300V.ANTAL_BORN AS ANTAL_BOERN, 
                         dbo.JY64300V.ADR_TILFLYT_TS AS TIDSSTEMPLING_TILFLYTNING, dbo.JY64300V.VEJ_KODE AS VEJKODE, 
                         RTRIM(dbo.JY64300V.HUS_NUMMER) AS HUSNUMMER_BOGSTAV, RTRIM(dbo.JY64300V.ETAGE) AS ETAGE, RTRIM(dbo.JY64300V.SIDE_DORNR) AS SIDE, 
                         RTRIM(dbo.JY64300V.BYGNING_NUMMER) AS BYGNINGSNUMMER, dbo.JY64300V.ADR_FRAFLYT_TS AS TIDSSTEMPLING_FRAFLYTNING, RTRIM(dbo.JY64300V.CO_NAVN) AS CO_NAVN, 
                         dbo.JY64300V.KOM_TILFLYTDATO AS KOMMUNE_TILFLYTNINGSDATO, dbo.JY64300V.FRAFLYT_KOMMUNENR AS FRAFLYTNINGSKOMMUNENUMMER, 
                         dbo.JY64300V.ADRESSEBESKYT_DATO AS DATO_FOR_ADRESSEBESKYTTELSE, dbo.JY64300V.ADR_BESKYT_SLTDATO AS DATO_SLETNING_ADRESSEBESKYT, 
                         dbo.JY64300V.CIVILSTAND_TS AS TIDSSTEMPLING_CIVILSTAND, RTRIM(CAST(dbo.QL58800V.TEKST AS VARCHAR(75))) AS CIVILSTAND, 
                         dbo.JY64300V.CIVILST_OPHOR_TS AS TID_FOR_CIVILSTANDSOPHOER, dbo.JY64300V.PERSONNR_AGTEFALLE AS PERSONNUMMER_AEGTEFAELLE, 
                         RTRIM(dbo.JY64300V.AGTEFALLE_FLAG) AS FLAG_FOR_AEGTEFAELLE, dbo.JY64300V.LAND_KODE AS LANDEKODE, RTRIM(CAST(dbo.QL59400V.TEKST AS VARCHAR(75))) 
                         AS LAND, dbo.JY64300V.STATSB_RET_TS AS TID_FOR_AENDR_STATSBORGERSK, 
                         dbo.JY64300V.STATBORG_OPHOR_TS AS TID_FOR_OPHOER_STATSBORGERSK, dbo.JY64300V.PERSONNUMMER_MOR, dbo.JY64300V.PERSONNUMMER_FAR, 
                         RTRIM(dbo.JY64300V.MOR_DOK) AS MOR_DOK, RTRIM(dbo.JY64300V.FAR_DOK) AS FAR_DOK, dbo.JY64300V.BORGERSTATUS_UM AS USIK_TIDSTEMPEL_BORGERSTATUS, 
                         CAST(dbo.JY64300V.KOMMUNENUMMER AS VARCHAR(3)) + RIGHT('0000' + CONVERT(VARCHAR, dbo.JY64300V.VEJ_KODE), 4) 
                         + RTRIM(dbo.JY64300V.HUS_NUMMER) AS ADRESSELINK_ID, CAST(dbo.JY64300V.KOMMUNENUMMER AS VARCHAR(3)) 
                         + CAST(dbo.JY64300V.VEJ_KODE AS VARCHAR(4)) + RTRIM(dbo.JY64300V.HUS_NUMMER) AS ADRESSE_ID, 
                         CAST(dbo.JY64300V.KOMMUNENUMMER AS VARCHAR(3)) + CAST(dbo.JY64300V.VEJ_KODE AS VARCHAR(4)) + RTRIM(dbo.JY64300V.HUS_NUMMER) 
                         + LTRIM(dbo.JY64300V.ETAGE) + LTRIM(dbo.JY64300V.SIDE_DORNR) AS UDVADRESSEID, dbo.JY64300V.PERSONNUMMER
FROM            dbo.JY64300V LEFT OUTER JOIN
                         dbo.QL58900V ON dbo.JY64300V.BORGERSTATUS_KODE = dbo.QL58900V.KODE LEFT OUTER JOIN
                         dbo.QL58800V ON dbo.JY64300V.CIVILSTAND = dbo.QL58800V.KODE LEFT OUTER JOIN
                         dbo.QL59400V ON dbo.JY64300V.LAND_KODE = dbo.QL59400V.KODE LEFT OUTER JOIN
                         dbo.JY72000V ON dbo.JY64300V.KOMMUNENUMMER = dbo.JY72000V.KOMMUNENUMMER AND dbo.JY64300V.VEJ_KODE = dbo.JY72000V.VEJKODE AND 
                         dbo.JY64300V.HUS_NUMMER = dbo.JY72000V.HUS_NR